[project]
name = "code-analysis-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "karry", email = "1033588792@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "icecream>=2.2.0",
    "openai>=3.14.1",
]

[project.scripts]
code-analysis-system = "code_analysis_system:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
