[project]
name = "code-analysis-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "karry", email = "1033588792@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "faiss-cpu>=1.15.1",
    "icecream>=2.2.0",
    "jieba>=0.42.1",
    "langchain-community>=0.4.2",
    "langchain-ollama>=1.1.0",
    "openai>=3.14.1",
    "rank-bm25>=0.2.2",
]

[project.scripts]
code-analysis-system = "code_analysis_system:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
